language: bash

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get update && sudo apt-get install -y shellcheck

script:
        - ls -l
        - bash test.sh
        - ls -l
        - pwd
        - cat file
notifications:
  email:
    on_success: never
